apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webapp
secretGenerator:
- name: redis-pass
  literals:
  - password=patata
resources:
  - np.yaml
  - storage-class.yaml
  - redis-leader.yaml
  - redis-follower.yaml
  - flask-deployment.yaml
  - networking.yaml
